begin
create (_0:`Restaurant` {`code`:"RJOAO", `name`:"Restaurante de João"})
create (_1:`Item` {`code`:"CHEESE-BURGER", `label`:"Cheese Burger"})
create (_2:`Item` {`code`:"FANTA", `label`:"Fanta"})
create (_3:`Item` {`code`:"COCA_COLA", `label`:"Coca-Cola"})
create (_4:`Item` {`code`:"BATATA_FRITA", `label`:"Batata Frita"})
create (_5:`Item` {`code`:"MANDIOCA_FRITA", `label`:"Mandioca Frita"})
create (_6:`Item` {`code`:"DOUBLE-CHEESE-BACON", `label`:"Double Cheese Burger"})
create (_7:`ItemGroup` {`code`:"PORCOES", `label`:"Porç?es"})
create (_8:`ItemGroup` {`code`:"BEBIDAS", `label`:"Bebidas"})
create (_9:`ItemGroup` {`code`:"LANCHES", `label`:"Lanches"})
create (_10:`OptionGroup` {`label`:"Tamanho Refrigerante"})
create (_11:`OptionGroup` {`label`:"Adicionais"})
create (_12:`Option` {`label`:"Bacon Picado", `type`:"TOPIC"})
create (_13:`Option` {`label`:"600 ml", `type`:"SIZE"})
create (_14:`Option` {`label`:"350 ml", `type`:"SIZE"})
create (_15:`Option` {`label`:"Parmes?o Ralado", `type`:"TOPIC"})
create (_16:`Option` {`label`:"2 L", `type`:"SIZE"})
create (_17:`Menu` {`code`:"RJOAO_MENU_V01"})
create (_18:`ItemCombo` {`label`:"Batata-Frita mais 2 Fantas"})
create (_19:`Item` {`code`:"CHEESE-ORION", `label`:"Cheese Orion"})
create (_20:`Item` {`code`:"HAMBURGER", `label`:"Hamburger"})
create (_21:`CommonItemPool` {`code`:"REFRIGERANTES"})
create (_22:`Restaurant` {`code`:"MCDONALDSCAMBUI", `name`:"McDonalds Cambui"})
create (_23:`Chain` {`code`:"REDEMCDONALDS", `name`:"Rede McDonalds"})
create (_24:`ItemGroup` {`code`:"LANCHES-SELECIONADOS", `label`:"Lanches Selecionados"})
create (_25:`Menu` {`code`:"MENU_MCDONALDS_CAMBUI"})
create (_26:`ChainMenu` {`code`:"CHAIN_MENU_MCDONALDS"})
create (_27:`Item` {`code`:"MCCHICKEN", `label`:"McChicken"})
create (_28:`Item` {`code`:"BIG-TASTY", `label`:"BigTasty"})
create (_29:`Item` {`code`:"BIG-MAC", `label`:"BigMac"})
create (_30:`Item` {`code`:"QUARTEIRAO", `label`:"Quarteir?o"})
create (_31:`Item` {`code`:"FANTA", `label`:"Fanta"})
create (_32:`Item` {`code`:"COCA_COLA", `label`:"Coca-Cola"})
create (_33:`ItemGroup` {`code`:"LANCHES-MCDONALDS", `label`:"Lanches"})
create (_34:`ItemGroup` {`code`:"BEBIDAS-MCDONALDS", `label`:"Bebidas"})
create (_35:`OptionGroup` {`label`:"Tamanho Refrigerante"})
create (_36:`Option` {`label`:"2 L", `type`:"SIZE"})
create (_37:`Option` {`label`:"350 ml", `type`:"SIZE"})
create (_38:`Option` {`label`:"600 ml", `type`:"SIZE"})
create (_39:`Menu` {`code`:"MCDONALDS_PADRAO_CHAIN"})
create (_40:`ItemGroup` {`code`:"COMBOS", `label`:"Combos"})
create (_41:`ItemCombo` {`label`:"Batata-Frita mais 2 Fantas"})
create (_42:`OptionGroup` {`label`:"Adicionais"})
create (_43:`Option` {`label`:"Parmes?o Ralado", `type`:"TOPIC"})
create (_44:`Option` {`label`:"Bacon Picado", `type`:"TOPIC"})
create (_0)-[:`HAVE_MENU`]->(_17)
create (_2)-[:`HAVE_OPTION_GROUP`]->(_10)
create (_3)-[:`HAVE_OPTION_GROUP`]->(_10)
create (_4)-[:`HAVE_OPTION_GROUP` {`restaurantCode`:"RJOAO"}]->(_11)
create (_5)-[:`HAVE_OPTION_GROUP` {`restaurantCode`:"RJOAO"}]->(_11)
create (_7)-[:`HAVE_ITEM_COMBO` {`restaurantCode`:"RJOAO"}]->(_18)
create (_7)-[:`HAVE_ITEM` {`order`:1, `startPrice`:"28.50", `restaurantCode`:"RJOAO"}]->(_5)
create (_7)-[:`HAVE_ITEM` {`order`:1, `startPrice`:"23.50", `restaurantCode`:"RJOAO"}]->(_4)
create (_8)-[:`HAVE_ITEM` {`order`:1, `startPrice`:"23.50", `restaurantCode`:"RJOAO"}]->(_2)
create (_8)-[:`HAVE_ITEM` {`order`:1, `startPrice`:"9.50", `restaurantCode`:"RJOAO"}]->(_3)
create (_9)-[:`HAVE_ITEM` {`order`:1, `startPrice`:"23.50", `restaurantCode`:"RJOAO"}]->(_6)
create (_9)-[:`HAVE_ITEM` {`order`:1, `startPrice`:"18.50", `restaurantCode`:"RJOAO"}]->(_1)
create (_9)-[:`HAVE_ITEM` {`order`:1, `startPrice`:"15.50", `restaurantCode`:"RJOAO"}]->(_1)
create (_10)-[:`HAVE_OPTION` {`order`:2, `startPrice`:"6.50"}]->(_13)
create (_10)-[:`HAVE_OPTION` {`order`:1, `startPrice`:"4.50"}]->(_14)
create (_10)-[:`HAVE_OPTION` {`order`:2, `startPrice`:"10.50"}]->(_16)
create (_11)-[:`HAVE_OPTION` {`order`:2, `startPrice`:"4", `restaurantCode`:"RJOAO"}]->(_15)
create (_11)-[:`HAVE_OPTION` {`order`:1, `startPrice`:"3", `restaurantCode`:"RJOAO"}]->(_12)
create (_17)-[:`HAVE_ITEM_GROUP` {`available`:true}]->(_9)
create (_17)-[:`HAVE_ITEM_GROUP` {`available`:true}]->(_8)
create (_17)-[:`HAVE_ITEM_GROUP` {`available`:true}]->(_7)
create (_18)-[:`HAVE_COMBO_ITEM` {`qty`:1, `restaurantCode`:"RJOAO"}]->(_4)
create (_22)-[:`BELONGS_TO_A_CHAIN`]->(_23)
create (_22)-[:`HAVE_MENU`]->(_25)
create (_23)-[:`HAVE_CHAIN_MENU`]->(_26)
create (_25)-[:`HAVE_ITEM_GROUP` {`available`:true}]->(_24)
create (_31)-[:`HAVE_OPTION_GROUP`]->(_35)
create (_32)-[:`HAVE_OPTION_GROUP`]->(_35)
create (_33)-[:`HAVE_ITEM` {`order`:1, `startPrice`:"77.50", `restaurantCode`:"MCDONALDSCAMBUI"}]->(_27)
create (_33)-[:`HAVE_ITEM` {`available`:true, `chainCode`:"REDEMCDONALDS", `order`:1, `startPrice`:"18.50", `restaurantCode`:"MCDONALDSCAMBUI"}]->(_28)
create (_33)-[:`HAVE_ITEM` {`available`:true, `chainCode`:"REDEMCDONALDS", `order`:1, `startPrice`:"15.50"}]->(_29)
create (_33)-[:`HAVE_ITEM` {`chainCode`:"REDEMCDONALDS", `order`:1, `startPrice`:"33.50"}]->(_27)
create (_33)-[:`HAVE_ITEM` {`chainCode`:"REDEMCDONALDS", `order`:1, `startPrice`:"23.50"}]->(_30)
create (_34)-[:`HAVE_ITEM` {`available`:true, `chainCode`:"REDEMCDONALDS", `order`:1, `startPrice`:"9.50"}]->(_32)
create (_34)-[:`HAVE_ITEM` {`order`:1, `startPrice`:"23.50", `restaurantCode`:"MCDONALDSCAMBUI"}]->(_31)
create (_35)-[:`HAVE_OPTION` {`order`:2, `startPrice`:"10.50"}]->(_36)
create (_35)-[:`HAVE_OPTION` {`order`:1, `startPrice`:"4.50"}]->(_37)
create (_35)-[:`HAVE_OPTION` {`order`:2, `startPrice`:"6.50"}]->(_38)
create (_39)-[:`BASED_ON_CHAIN_MENU`]->(_26)
create (_39)-[:`HAVE_ITEM_GROUP` {`available`:true}]->(_33)
create (_39)-[:`HAVE_ITEM_GROUP` {`available`:true}]->(_34)
create (_40)-[:`HAVE_ITEM_COMBO` {`restaurantCode`:"MCDONALDSCAMBUI"}]->(_41)
create (_41)-[:`HAVE_COMBO_ITEM` {`qty`:1, `restaurantCode`:"MCDONALDSCAMBUI"}]->(_29)
create (_42)-[:`HAVE_OPTION` {`order`:2, `startPrice`:"4", `restaurantCode`:"MCDONALDSCAMBUI"}]->(_43)
create (_42)-[:`HAVE_OPTION` {`available`:true, `chainCode`:"REDEMCDONALDS", `order`:1, `startPrice`:"3"}]->(_44)
create (_42)-[:`HAVE_OPTION` {`available`:true, `order`:1, `startPrice`:"3", `restaurantCode`:"MCDONALDSCAMBUI"}]->(_44)
;
commit